### ISSUE TITLE
meals function not working

### ISSUE THREAD

**Issue by eujon** [lukaszmielczarekdev/daily-diet#1]
![image](https://user-images.githubusercontent.com/84864040/177986920-a7f6bd2a-a83c-4232-a13e-089a54e39050.png)
After clicking on creating new meal under meals, it brings me back to diary creator

**Comment by lukaszmielczarekdev** [comment]
Hi,
Thanks for the info, I am very happy :)

For now, this is a temporary solution as there is no separate creator for meals, so you use the diary creator where you can save a meal as a template.

There should be a separate creator for meals.

Thanks again!

**Comment by lukaszmielczarekdev** [comment]
Because you opened a new issue with the same question, so I deleted this comment and replied to the open issue, so that we would have order and thread for discussion.
